### ISSUE TITLE
Player score decrement keybinds

### ISSUE THREAD

**Issue by Velyks** [punlife/Punduction-release#1]
**Is your feature request related to a problem? Please describe.**
Not exactly.

**Describe the solution you'd like**
A mirror of the current "Increment player x score" keybinding, but to decrement the score.

**Describe alternatives you've considered**
A horrible Autohotkey macro to find the down arrow in the player window.

**Additional context**
Sometimes I accidentally double-tap a button or press the wrong one on my macro keyboard, it would be nice to be able to fully adjust scores.

**Comment by punlife** [comment]
This shouldn't be difficult to do in the slightest, I'll add it to my log of requests

**Comment by punlife** [comment]
This should be in the new version, sorry it took so long to release!
